-- Count of crimes by type

SELECT
    CRIMETYPESDIM.DELITO,
    COUNT(FACTCRIMES.DELITOID) AS TOTAL_CRIMES
FROM
    FACTCRIMES
    JOIN CRIMETYPESDIM ON FACTCRIMES.DELITOID = CRIMETYPESDIM.DELITOID
GROUP BY
    CRIMETYPESDIM.DELITO
ORDER BY
    TOTAL_CRIMES DESC;

-- Homicides tru the months grouped by years

SELECT
    COUNT(FACTCRIMES.*)  AS Total,
    DATEDIM.YEAR,
    DATEDIM.MONTHNAME
FROM 
    FACTCRIMES
    LEFT JOIN DATEDIM ON DATEDIM.FECHAID = FACTCRIMES.FECHAID
    LEFT JOIN CRIMETYPESDIM ON CRIMETYPESDIM.DELITOID = FACTCRIMES.DELITOID
WHERE CRIMETYPESDIM.DELITO = 'HOMICIDIO'
GROUP BY DATEDIM.YEAR, DATEDIM.MONTHNAME;

--



